### ISSUE TITLE
Process suspend when idea connects to port

### ISSUE THREAD

**Issue by maybe-why-not** [JetBrains/jdk-sa-jdwp#12]
### env
```
windows 10
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)
```
### error
The process is suspended when running the command, and the process is also suspended when the idea connects to the port. AND web service not working
```
command：java -cp .;"C:\Program Files\Java\jdk1.8.0_221\lib\sa-jdi.jar";"C:\Program Files\Java\jdk1.8.0_221\lib\tools.jar";sa-jdwp.jar com.jetbrains.sa.SaJdwpListeningServer 18292
```
![268f12f52e5fd972d75dccefc91be1c](https://user-images.githubusercontent.com/29968903/161811746-96005349-40b5-45d9-8360-12b9cf979512.png)

When the tomcat startup parameter does not contain "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005", can sa-jdwp open a debug port without restarting tomcat?

**Comment by gorrus** [comment]
It should suspend the app, that's how it works. Generally speaking you should attach from the IDEA "attach to process" action. If you do this manually, you may need to press pause in the IDEA debugger UI after attach.

**Comment by maybe-why-not** [comment]
### When the tomcat startup parameter does not contain "-Xdebug"
The process is suspended when i attach from the IDEA "attach to process" action，I didn't set any breakpoints, but IDEA debugger stop in
```
C:\Program Files\Java\jdk1.8.0_221\jre\lib\rt.jar!\java\net\DualStackPlainSocketImpl.class:223
    static native int accept0(int var0, InetSocketAddress[] var1) throws IOException;
```
tomcat process is suspended, web service not working, IDEA debugger also stop working, i can't press f7 or f8, idea loses the ability to debug.
![image](https://user-images.githubusercontent.com/29968903/161880541-3b2f7836-d454-4856-b744-a2d194ef1af3.png)
### When the tomcat startup parameter contain "-Xdebug"
"attach to process" is working
### enhancement
Many times I need to debug a docker container where tomcat is deployed. As the main process of docker, tomcat cannot be restarted, so I cannot add "-Xdebug" and restart tomcat.
So I need an attachable-debugger agent, you don't need tomcat to start in debug mode, inject the agent and open the debug port without restarting tomcat.

**Comment by gorrus** [comment]
It is not possible with "standard" jvms (I think SAP implemented this in their jvm): you need to start the process with the debug agent to be able to attach and debug later. Sa-jdwp library can attach and provide some debugging capabilities like showing stack frames, variable values etc, but not stepping or breakpoints.

**Comment by maybe-why-not** [comment]
thank you, look good to me.
