### ISSUE TITLE
Target process stucks at Unsafe#park

### ISSUE THREAD

**Issue by Cubxity** [JetBrains/jdk-sa-jdwp#9]
**Java Info:**
```
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
```

**Description:**

I've tried attaching to a target process using `com.jetbrains.sa.SaJdwpListeningServer` with PID and PORT argument. The target process froze once my debugger attached to the server. Threads were waiting at Unsafe#park. This happens the same when I ran my project with normal "run" and then used the attach debugger button. The target process is luyten and my project is javafx based.

**Comment by gorrus** [comment]
This looks correct, target process is fully suspended once attached. This is not a regular debugger, think about more like an extended thread dump, which allows to see variables values, etc. Just like a debugger when stopped somewhere, but without breakpoints, ability to step. You have to detach to allow your app to continue.

**Comment by Cubxity** [comment]
@gorrus is it possible to use it to make something like intellij's debugger? Like allow the process to run and you can still view threads and such and place breakpoints etc..

**EDIT:** Also when calling vm#resume doesn't resume the target process

**Comment by gorrus** [comment]
Not really, it is not indended to replace or emulate the debugger.

**Comment by Cubxity** [comment]
@gorrus is it this library that suspends the program or is it java?

**Comment by gorrus** [comment]
The library uses Java Serviceablility Agent API, the program is suspended by the OS.

**Comment by Cubxity** [comment]
@gorrus so if it's not related to this lib, are there ways to unsuspend it?

**Comment by gorrus** [comment]
If you're using the library - detach should resume the app

**Comment by Cubxity** [comment]
@gorrus would that means that I cannot debug the process anymore? (set breakpoints, etc.?)

**Comment by gorrus** [comment]
after you detach, you can attach again when you need
